### ISSUE TITLE
Lambertian normalization

### ISSUE THREAD

**Issue by rodluger** [rodluger/starrynight#4]
@ericagol can you check my reasoning here:

https://github.com/rodluger/starrynight/blob/1506dc8d6b9592815aaafcfa39a2d83448b1d547/tex/ms.tex#L1850

I would like to argue that my units are correct based on this, but I'm not sure how. 

Specifically, my units imply that a body
 
- of unit radius
- a unit distance away from an illumination source
- of unit geometric albedo
- seen at full phase

will contribute the same flux as the source at the observer. I'm struggling to justify this. Can you take a look?

**Comment by ericagol** [comment]
Maybe we can chat about this at some point?
